version: '3.7'

services:
    apolo-health-care:
        container_name: apolo-health-care
        build:
            context: ..
        restart: unless-stopped
        ports:
            - '8080:8080'
        networks:
            - apolo_network
        depends_on:
            - postgresql
            - redis
    postgresql:
        container_name: postgresql
        image: postgres:16.3
        restart: always
        healthcheck:
            test: [ 'CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}' ]
            interval: 5s
            timeout: 5s
            retries: 10
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: apolo-health-care
        ports:
            - "5432:5432"
        volumes:
            - ./.docker/postgres:/var/lib/postgresql/data
        networks:
            - apolo_network
    redis:
        container_name: redis
        image: redis:7.2.4
        ports:
            - '6379:6379'
        networks:
            - apolo_network

networks:
    apolo_network:
        driver: bridge