name: 'apolo'

services:
    postgresql:
        container_name: postgresql
        image: postgres:16.3
        restart: always
        healthcheck:
            test: [ 'CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}' ]
            interval: 5s
            timeout: 5s
            retries: 10
        environment:
            POSTGRES_USER: ${DB_POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD:-1234}
        ports:
            - "5432:5432"
        volumes:
            - ../.docker/postgres:/var/lib/postgresql/data
        networks:
            - apolo_services
    redis:
        container_name: redis
        image: redis:7.2.4
        ports:
            - '6379:6379'
        networks:
            - apolo_services

networks:
    apolo_services:
        driver: bridge