name: CI Pipeline

on:
    pull_request:
        branches:
            - main
            - master
            - develop
            - 'hotfix/**'
            - 'release/**'
    push: # Remove
        branches:
            - 'feature/**'
            - 'bugfix/**'
            - 'ci/**'
    workflow_dispatch:

jobs:
    tests:
        name: Tests runner
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Set Up JDK@21
                uses: actions/setup-java@v3
                with:
                    java-version: '21'
                    distribution: 'temurin'
            -   name: Run application test
                run: ./gradlew test

    build_push_image:
        name: Build and Push Image
        needs: tests
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Set Up JDK@21
                uses: actions/setup-java@v3
                with:
                    java-version: '21'
                    distribution: 'temurin'
            -   name:  Setup Gradle
                uses:  gradle/gradle-build-action@v3
            -   name: Set BUILD_TAG
                run: echo BUILD_TAG=$(echo ${{ github.head_ref || github.ref_name }} | sed "s,/,_,g")-${{ github.run_number }} >> $GITHUB_ENV
            -   name: Build Image
                run: ./gradlew bootBuildImage --imageName=${{ env.IMAGE_NAME }}:${{ env.BUILD_TAG }}
            -   name: Set BUILD_TAG
                run: echo BUILD_TAG=$(echo ${{ github.head_ref || github.ref_name }} | sed "s,/,_,g")-${{ github.run_number }} >> $GITHUB_ENV
            # Opcional: Login e Push para o Docker Hub
            -  name: Log in to Docker Hub
               if: github.ref == 'refs/heads/main' # Só executa no branch principal
               uses: docker/login-action@v2
               with:
                   username: ${{ secrets.DOCKER_HUB_USER }}
                   password: ${{ secrets.DOCKER_HUB_PWD }}
            - name: Push Image
              if: github.ref == 'refs/heads/main' # Só executa no branch principal
              run: docker push ${{ env.IMAGE_NAME }}:${{ env.BUILD_TAG }}