name: Deploy Pipeline

on:
    pull_request:
        branches:
            - main
            - 'hotfix/**'
            - 'release/**'
        types:
            - closed
    workflow_dispatch:

env:
    IMAGE_NAME: thiagodd/apolo-health-care

jobs:
    tests:
        if: github.event.pull_request.merged == true
        name: Tests runner
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Set Up JDK@21
                uses: actions/setup-java@v3
                with:
                    java-version: '21'
                    distribution: 'temurin'
            -   name: Run application test
                run: ./gradlew test

    build_push_image:
        if: github.event.pull_request.merged == true
        name: Build and Push Image
        needs: tests
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Set Up JDK@21
                uses: actions/setup-java@v3
                with:
                    java-version: '21'
                    distribution: 'temurin'
            -   name:  Setup Gradle
                uses:  gradle/gradle-build-action@v3
            -   name: Build Image
                run: ./gradlew bootBuildImage --imageName=${{ env.IMAGE_NAME }}:latest
            -  name: Log in to Docker Hub
               uses: docker/login-action@v2
               with:
                   username: ${{ secrets.DOCKER_HUB_USER }}
                   password: ${{ secrets.DOCKER_HUB_PWD }}
            - name: Push Image
              run: docker push ${{ env.IMAGE_NAME }}:latest