name: Deploy Pipeline

on:
    pull_request:
        branches:
            - main
            - 'hotfix/**'
            - 'release/**'
        types:
            - closed
    workflow_dispatch:

env:
    IMAGE_NAME: thiagodd/apolo-health-care
    IMAGE_TAG: 0.0.1

jobs:
    tests:
        if: github.event.pull_request.merged == true
        name: Tests runner
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Set Up JDK@21
                uses: actions/setup-java@v3
                with:
                    java-version: '21'
                    distribution: 'temurin'
            -   name: Run application test
                run: ./gradlew test

    build_app_image:
        name: Build Application and Docker Image
        needs: tests
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   uses: actions/checkout@v3
            -   name: Set Up JDK@21
                uses: actions/setup-java@v3
                with:
                    java-version: '21'
                    distribution: 'temurin'
            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v3
            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v3
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            -   name: Login to Docker Hub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKER_HUB_USER }}
                    password: ${{ secrets.DOCKER_HUB_PWD }}
            -   name: Concat name with tag
                run: |
                    echo FULL_IMAGE_NAME=${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} >> $GITHUB_ENV
            -   name: Build and push
                uses: docker/build-push-action@v4
                with:
                    context: .
                    push: true
                    tags: ${{ env.FULL_IMAGE_NAME }}
            -   name: Build and push tag latest
                uses: docker/build-push-action@v4
                with:
                    context: .
                    push: true
                    tags: ${{ env.IMAGE_NAME }}:latest
